#配置数据源：
spring:
  datasource:
      url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
      username: root
      password: root

#配置mybatis
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml

#log
logging:
  level:
    com.cy: debug
